import time

def cielo():
    print()
    print("¡¡¡ENHORABUENA!!!")
    print()
    print()
    print("Su nivel de pecado es 0")
    print()
    print("Disfrute del cielo")
    print()
    while True:
        time.sleep(10)
        print("'El cielo es un ahora que permanece.' - San Gregorio Magno")
        print()
        time.sleep(10)
        print("'Ver a Dios cara a cara.' - San Agustín de Hipona")
        print()
        time.sleep(10)
        print("'La patria es el cielo.' - Santa Teresa de Ávila")
        print()
        time.sleep(10)
        print("'La verdadera vida es en Dios.' - Santa Catalina de Siena")
        print()
        time.sleep(10)
        print("'Un eterno abrazo de amor.' - San Juan de la Cruz")
        print()
        time.sleep(10)
        print("'El cielo es la felicidad eterna.' - San Alfonso María de Ligorio")
        print()
        time.sleep(10)
        print("'Allí veremos, allí amaremos, allí alabaremos.' - San Agustín de Hipona")
        print()
        time.sleep(10)
        print("'El cielo es el descanso en Dios.' - Santo Tomás de Aquino")
        print()
        time.sleep(10)
        print("'La recompensa de nuestra fe.' - San Ambrosio de Milán")
        print()
        time.sleep(10)