import time

def infierno():
    print()
    print("TU DESTINO ES EL INFIERNO")
    print()
    print()
    print("Su nivel de pecado es MÁXIMO")
    print()
    print("Asuma las consecuencias de sus actos")
    print()
    while True:
        time.sleep(2)
        print("Soberbia ")
        print()
        time.sleep(2)
        print("Avaricia ")
        print()
        time.sleep(2)
        print("Lujuria")
        print()
        time.sleep(2)
        print("Ira")
        print()
        time.sleep(2)
        print("Gula")
        print()
        time.sleep(2)
        print("Envidia")
        print()
        time.sleep(2)
        print("Pereza ")
        print()
